<!DOCTYPE html>
<html lang="en-us">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="theme" content="hugo-academic">
  <meta name="generator" content="Hugo 0.18.1" />
  <meta name="author" content="Wanting Zhai">
  <meta name="description" content="Biostatistics Master Student">

  
  
  
  
    
    
    <link rel="stylesheet" href="/css/highlight.min.css">
    
  
  <link rel="stylesheet" href="/css/bootstrap.min.css">
  <link rel="stylesheet" href="/css/font-awesome.min.css">
  <link rel="stylesheet" href="/css/academicons.min.css">
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lato:400,700|Merriweather|Roboto+Mono">
  <link rel="stylesheet" href="/css/hugo-academic.css">
  

  <link rel="alternate" href="/index.xml" type="application/rss+xml" title="Wanting Zhai">
  <link rel="feed" href="/index.xml" type="application/rss+xml" title="Wanting Zhai">

  <link rel="icon" type="image/png" href="/img/icon.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/apple-touch-icon.png">

  <link rel="canonical" href="/post/march-14-2017-pre-class/">

  

  <title>March 14, 2017 Pre-Class | Wanting Zhai</title>

</head>
<body id="top" data-spy="scroll" data-target="#navbar-main" data-offset="71">

<nav class="navbar navbar-default navbar-fixed-top" id="navbar-main">
  <div class="container">

    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target=".navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Wanting Zhai</a>
    </div>

    
    <div class="collapse navbar-collapse">

      
      <ul class="nav navbar-nav navbar-right">
        

        

        <li class="nav-item">
          <a href="/#about">
            
            <span>Home</span>
          </a>
        </li>

        
        

        

        <li class="nav-item">
          <a href="/#posts">
            
            <span>Posts</span>
          </a>
        </li>

        
        

        

        <li class="nav-item">
          <a href="/#projects">
            
            <span>Projects</span>
          </a>
        </li>

        
        

        

        <li class="nav-item">
          <a href="/#contact">
            
            <span>Contact</span>
          </a>
        </li>

        
        
      </ul>

    </div>
  </div>
</nav>


<article class="article" itemscope itemtype="http://schema.org/Article">

  

  <div class="article-container">
    <h1 itemprop="name">March 14, 2017 Pre-Class</h1>
    

<div class="article-metadata">

  <span class="article-date">
    <time datetime="2017-03-13 00:00:00 &#43;0000 UTC" itemprop="datePublished">
      Mon, Mar 13, 2017
    </time>
  </span>

  

  

  
  
<div class="share-box" aria-hidden="true">
  <ul class="share">
    <li>
      <a class="facebook"
         href="https://www.facebook.com/sharer.php?u=%2fpost%2fmarch-14-2017-pre-class%2f"
         target="_blank">
        <i class="fa fa-facebook"></i>
      </a>
    </li>
    <li>
      <a class="twitter"
         href="https://twitter.com/intent/tweet?text=March%2014%2c%202017%20Pre-Class&amp;url=%2fpost%2fmarch-14-2017-pre-class%2f"
         target="_blank">
        <i class="fa fa-twitter"></i>
      </a>
    </li>
    <li>
      <a class="linkedin"
         href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fpost%2fmarch-14-2017-pre-class%2f&amp;title=March%2014%2c%202017%20Pre-Class"
         target="_blank">
        <i class="fa fa-linkedin"></i>
      </a>
    </li>
    <li>
      <a class="weibo"
         href="http://service.weibo.com/share/share.php?url=%2fpost%2fmarch-14-2017-pre-class%2f&amp;title=March%2014%2c%202017%20Pre-Class"
         target="_blank">
        <i class="fa fa-weibo"></i>
      </a>
    </li>
    <li>
      <a class="email"
         href="mailto:?subject=March%2014%2c%202017%20Pre-Class&amp;body=%2fpost%2fmarch-14-2017-pre-class%2f">
        <i class="fa fa-envelope"></i>
      </a>
    </li>
  </ul>
</div>


  

</div>

    <div class="article-style" itemprop="articleBody">
      <!-- BLOGDOWN-HEAD -->
<!-- /BLOGDOWN-HEAD -->

<!-- BLOGDOWN-BODY-BEFORE -->
<!-- /BLOGDOWN-BODY-BEFORE -->
<div id="project-goals" class="section level1">
<h1>Project Goals:</h1>
<p>With this project we will simulate a famoues probability problem. This will not require knowledge of probability or statistics but only the logic to follow the steps in order to simulate this problem. This is one way to solve problems by using the computer.</p>
<ol style="list-style-type: decimal">
<li><strong>Gambler’s Ruin</strong>: Suppose you have a bankroll of $1000 and make bets of $100 on a fair game. By simulating the outcome directly for at most 5000 iterations of the game (or hands), estimate:
<ol style="list-style-type: lower-alpha">
<li>the probability that you have “busted” (lost all your money) by the time you have placed your one hundredth bet.</li>
<li>the probability that you have busted by the time you have placed your five hundredth bet by simulating the outcome directly.</li>
<li>the mean time you go bust, given that you go bust within the first 5000 hands.</li>
<li>the mean and variance of your bankroll after 100 hands (including busts).</li>
<li>the mean and variance of your bankroll after 500 hands (including busts).</li>
</ol></li>
</ol>
<pre class="r"><code>set.seed(1)
GR=function(bet,bankroll,p)
{
  k=0
  while(bet&gt;0) {
    ProbVal=runif(1)
    if(ProbVal &lt;= p)
    {
      bankroll = bet + bankroll
      bet = (bet + bankroll)*0.1
    }else{
      bankroll = bankroll-bet
      bet = bet
      }
    k=k+1
    if(bankroll &lt; bet){break}
  }
  duration = k
  return(duration)
}

durations = numeric()
s = 5000
for(i in 1:s)
{
  nextd = GR(100,900,0.5)
  durations = c(durations,nextd)
}</code></pre>
<div id="a" class="section level3">
<h3>a</h3>
<pre class="r"><code>a=length(durations)
b=length(which(durations&lt;=100))
prob=b/a
prob</code></pre>
<pre><code>## [1] 0.1198</code></pre>
<p>The probability that you have “busted” (lost all your money) by the time you have placed your one hundredth is 0.1198</p>
</div>
<div id="b" class="section level3">
<h3>b</h3>
<pre class="r"><code>a=length(durations)
b=length(which(durations&lt;=500))
prob=b/a
prob</code></pre>
<pre><code>## [1] 0.4774</code></pre>
<p>The probability that you have busted by the time you have placed your five hundredth bet by simulating the outcome directly is 0.4774</p>
</div>
<div id="c" class="section level3">
<h3>c</h3>
<pre class="r"><code>a=durations[which(durations&lt;=5000)]
mean=mean(a)
mean</code></pre>
<pre><code>## [1] 757.8801</code></pre>
<p>The mean time you go bust, given that you go bust within the first 5000 hands is 757.8801</p>
</div>
<div id="d" class="section level3">
<h3>d</h3>
<pre class="r"><code>set.seed(1)
GR1=function(bet,bankroll,p)
{
  k=0
  while(bet&gt;0) {
    ProbVal=runif(1)
    if(ProbVal &lt;= p)
    {
      bankroll = bet + bankroll
      bet = (bet + bankroll)*0.1
    }else{
      bankroll = bankroll-bet
      bet = bet
      }
    k=k+1
    if(k ==100){break}
    if(bankroll&lt;bet){break}
  }
  duration = k
  return(bankroll)
  
}

bankroll=numeric()
s = 5000
for(i in 1:s)
{
  nextb = GR1(100,900,0.5)
  bankroll=c(bankroll,nextb)
}

mean(bankroll)</code></pre>
<pre><code>## [1] 879.2014</code></pre>
<pre class="r"><code>var(bankroll)</code></pre>
<pre><code>## [1] 2716298</code></pre>
<p>The mean of your bankroll after 100 hands (including busts) is 879.2014 The variance of your bankroll after 100 hands (including busts) is 2716298</p>
</div>
<div id="e" class="section level3">
<h3>e</h3>
<pre class="r"><code>set.seed(1)
GR2=function(bet,bankroll,p)
{
  k=0
  while(bet&gt;0) {
    ProbVal=runif(1)
    if(ProbVal &lt;= p)
    {
      bankroll = bet + bankroll
      bet = (bet + bankroll)*0.1
    }else{
      bankroll = bankroll-bet
      bet = bet
      }
    k=k+1
    if(k ==500){break}
    if(bankroll&lt; bet){break}
  }
  duration = k
  return(bankroll)
  
}

bankroll=numeric()
s = 5000
for(i in 1:s)
{
  nextb = GR2(100,900,0.5)
  bankroll=c(bankroll,nextb)
}

mean(bankroll)</code></pre>
<pre><code>## [1] 536.1681</code></pre>
<pre class="r"><code>var(bankroll)</code></pre>
<pre><code>## [1] 19437196</code></pre>
<p>The mean of your bankroll after 500 hands (including busts) is 536.1681 The variance of your bankroll after 500 hands (including busts) is 19437196</p>
<p>Note: you <em>must</em> stop playing if your player has gone bust. How will you handle this in the <code>for</code> loop?</p>
<ol start="2" style="list-style-type: decimal">
<li>Repeat the previous problem with betting on black in American roulette, where the probability of winning on any spin is 18/38 for an even payout.</li>
</ol>
<pre class="r"><code>set.seed(1)
GR=function(bet,bankroll,p)
{
  k=0
  while(bet&gt;0) {
    ProbVal=runif(1)
    if(ProbVal &lt;= p)
    {
      bankroll = bet + bankroll
      bet = (bet + bankroll)*0.1
    }else{
      bankroll = bankroll-bet
      bet = bet
      }
    k=k+1
    if(bankroll &lt; bet){break}
  }
  duration = k
  return(duration)
}

durations = numeric()
s = 5000
for(i in 1:s)
{
  nextd = GR(100,900,18/38)
  durations = c(durations,nextd)
}</code></pre>
</div>
<div id="a-1" class="section level3">
<h3>a</h3>
<pre class="r"><code>a=length(durations)
b=length(which(durations&lt;=100))
prob=b/a
prob</code></pre>
<pre><code>## [1] 0.1744</code></pre>
<p>The probability that you have “busted” (lost all your money) by the time you have placed your one hundredth is 0.1744</p>
</div>
<div id="b-1" class="section level3">
<h3>b</h3>
<pre class="r"><code>a=length(durations)
b=length(which(durations&lt;=500))
prob=b/a
prob</code></pre>
<pre><code>## [1] 0.6298</code></pre>
<p>The probability that you have busted by the time you have placed your five hundredth bet by simulating the outcome directly is 0.6298</p>
</div>
<div id="c-1" class="section level3">
<h3>c</h3>
<pre class="r"><code>a=durations[which(durations&lt;=5000)]
mean=mean(a)
mean</code></pre>
<pre><code>## [1] 504.1114</code></pre>
<p>The mean time you go bust, given that you go bust within the first 5000 hands is 504.1114</p>
</div>
<div id="d-1" class="section level3">
<h3>d</h3>
<pre class="r"><code>set.seed(1)
GR1=function(bet,bankroll,p)
{
  k=0
  while(bet&gt;0) {
    ProbVal=runif(1)
    if(ProbVal &lt;= p)
    {
      bankroll = bet + bankroll
      bet = (bet + bankroll)*0.1
    }else{
      bankroll = bankroll-bet
      bet = bet
      }
    k=k+1
    if(k ==100){break}
    if(bankroll&lt; bet){break}
  }
  duration = k
  return(bankroll)
  
}

bankroll=numeric()
s = 5000
for(i in 1:s)
{
  nextb = GR1(100,900,18/38)
  bankroll=c(bankroll,nextb)
}

mean(bankroll)</code></pre>
<pre><code>## [1] 463.9543</code></pre>
<pre class="r"><code>var(bankroll)</code></pre>
<pre><code>## [1] 864711.5</code></pre>
<p>The mean of your bankroll after 100 hands (including busts) is 463.9543 The variance of your bankroll after 100 hands (including busts) is 864711.5</p>
</div>
<div id="e-1" class="section level3">
<h3>e</h3>
<pre class="r"><code>set.seed(1)
GR2=function(bet,bankroll,p)
{
  k=0
  while(bet&gt;0) {
    ProbVal=runif(1)
    if(ProbVal &lt;= p)
    {
      bankroll = bet + bankroll
      bet = (bet + bankroll)*0.1
    }else{
      bankroll = bankroll-bet
      bet = bet
      }
    k=k+1
    if(k ==500){break}
    if(bankroll&lt; bet){break}
  }
  duration = k
  return(bankroll)
  
}

bankroll=numeric()
s = 5000
for(i in 1:s)
{
  nextb = GR2(100,900,18/38)
  bankroll=c(bankroll,nextb)
}

mean(bankroll)</code></pre>
<pre><code>## [1] 31.46429</code></pre>
<pre class="r"><code>var(bankroll)</code></pre>
<pre><code>## [1] 58251.21</code></pre>
<p>The mean of your bankroll after 500 hands (including busts) is 31.46429 The variance of your bankroll after 500 hands (including busts) is 58251.21</p>
<ol start="3" style="list-style-type: decimal">
<li><strong>Markov Chains</strong>. Suppose you have a game where the probability of winning on your first hand is 48%; each time you win, that probability goes up by one percentage point for the next game (to a maximum of 100%, where it must stay), and each time you lose, it goes back down to 48%. Assume you cannot go bust and that the size of your wager is a constant $100.
<ol style="list-style-type: lower-alpha">
<li>Is this a fair game? Simulate one hundred thousand sequential hands to determine the size of your return. Then repeat this simulation 99 more times to get a range of values to calculate the expectation.</li>
<li>Repeat this process but change the starting probability to a new value within 2% either way. Get the expected return after 100 repetitions. Keep exploring until you have a return value that is as fair as you can make it. Can you do this automatically?</li>
<li>Repeat again, keeping the initial probability at 48%, but this time change the probability increment to a value different from 1%. Get the expected return after 100 repetitions. Keep changing this value until you have a return value that is as fair as you can make it.</li>
</ol></li>
</ol>
</div>
<div id="a-2" class="section level3">
<h3>a</h3>
<pre class="r"><code>MC=function(bet,bankroll,p)
{
  k=0
  prob&lt;-p
  while(bet&gt;0) {
    ProbVal=runif(1)
    if(ProbVal &lt;= p)
    {
      bankroll = bankroll +bet
      p = p+0.01
    }else{
      bankroll = bankroll-bet
      p = prob
    }
    k=k+1
    if(k==100000){break}
    if(bankroll &lt; bet){break}
  }
  return(bankroll)
}

size = numeric()
s = 100
for(i in 1:s)
{
  nextb = MC(100,900,0.48)
  size = c(size,nextb)
}
mean(size)</code></pre>
<pre><code>## [1] 0</code></pre>
<p>This is not a fair game, since mean of size is 0.</p>
</div>
<div id="b-2" class="section level3">
<h3>b</h3>
<pre class="r"><code>set.seed(1)
proportion=numeric()
for (j in 1:20){
  size=numeric()
  s = 100
for(i in 1:s)
{
  nextb = MC(100,900,0.46+0.002*j)
  size = c(size,nextb)
}
  nextproportion=length(which(size==0))/100
  proportion=c(proportion,nextproportion)
}
proportion</code></pre>
<pre><code>##  [1] 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00
## [15] 0.96 0.94 0.88 0.80 0.71 0.67</code></pre>
<p>When starting probablity is 0.05, the result returns as fair as I can.</p>
</div>
<div id="c-2" class="section level3">
<h3>c</h3>
<pre class="r"><code>set.seed(1)
MC1=function(bet,bankroll,p,increment)
{
  k=0
  prob&lt;-p
  while(bet&gt;0) {
    ProbVal=runif(1)
    if(ProbVal &lt;= p)
    {
      bankroll = bankroll +bet
      p = p+increment
    }else{
      bankroll = bankroll-bet
      p = prob
    }
    k=k+1
    if(k==100000){break}
    if(bankroll &lt; bet){break}
  }
  return(bankroll)
}

proportion = numeric()
for (z in 1:20){
size=numeric()
s = 100
for(i in 1:s)
{
  nextb = MC1(100,900,0.48,0.002*z)
  size = c(size,nextb)
}
nextproportion=length(which(size==0))/100
proportion=c(proportion,nextproportion)
}
proportion</code></pre>
<pre><code>##  [1] 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 0.94 0.92 0.74 0.70 0.67 0.60
## [15] 0.57 0.57 0.50 0.39 0.38 0.34</code></pre>
<p>When probability increment to 0.034, the prportion of size of return equals to 0.5, which returns as fair as I can</p>
<ol start="4" style="list-style-type: decimal">
<li>For the last two examples in the previous question, you calculated a mean value. Because you saved these final results in a vector, use the bootstrap to estimate the variance of the return in each case for your final answer. Once you have these results, which game has the smaller variance in returns?</li>
</ol>
</div>
<div id="section" class="section level3">
<h3>4</h3>
<p>From 3(b)</p>
<pre class="r"><code>size=numeric()
s = 100
for(i in 1:s)
{
  nextb = MC(100,900,0.5)
  size = c(size,nextb)
}
set.seed(1)
b=sample(size,1000,replace=T)
mean(b)</code></pre>
<pre><code>## [1] 56049.7</code></pre>
<pre class="r"><code>var(b)</code></pre>
<pre><code>## [1] 10552396436</code></pre>
<p>From 3(c)</p>
<pre class="r"><code>size=numeric()
s = 100
for(i in 1:s)
{
  nextb = MC1(100,900,0.48,0.034)
  size = c(size,nextb)
}
set.seed(1)
b1=sample(size,1000,replace=T)
mean(b1)</code></pre>
<pre><code>## [1] 5834304</code></pre>
<pre class="r"><code>var(b1)</code></pre>
<pre><code>## [1] 2.417204e+13</code></pre>
<p>Game 3(b) has the smaller variance in returns.</p>
</div>
</div>

    </div>
  </div>

</article>

<div class="container">
  <nav>
  <ul class="pager">
    
    <li class="previous"><a href="/post/march-7-2017-in-class-project/"><span
      aria-hidden="true">&larr;</span> March 7, 2017 In-Class Project</a></li>
    

    
  </ul>
</nav>

</div>

<div class="article-container">
  
<section id="comments">
  <div id="disqus_thread"></div>
<script type="text/javascript">

(function() {
      
      
      if (window.location.hostname == "localhost")
                return;

      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      var disqus_shortname = 'wanting-zhai';
      dsq.src = 'https://' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</section>

</div>

<footer class="site-footer">
  <div class="container">
    <p class="powered-by">

      &copy; 2016 Your Name &middot; 

      Powered by the <a href="https://github.com/gcushen/hugo-academic" target="_blank">Academic
      theme</a> for <a href="http://gohugo.io" target="_blank">Hugo</a>.

      <span class="pull-right" aria-hidden="true">
        <a href="#" id="back_to_top">
          <span class="button_icon">
            <i class="fa fa-chevron-up fa-2x"></i>
          </span>
        </a>
      </span>

    </p>
  </div>
</footer>

    <script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.4/TweenMax.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/gsap/latest/plugins/ScrollToPlugin.min.js"></script>
    <script src="/js/jquery-1.12.3.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/isotope.pkgd.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.1/imagesloaded.pkgd.min.js"></script>
    <script src="/js/hugo-academic.js"></script>
    

    

    
    
      
      <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/highlight.min.js"></script>

      

      

      <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ['\\(','\\)']] } });
    </script>
    <script async src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML"></script>
    

  </body>
</html>

